on: 
  push: 
    branches:
      - '**'

env:
  DIST_DIR: ${{ github.workspace }}/build/dist

name: Build development release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source code
        uses: actions/checkout@v2
      
      - name: Define development release info
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          tag="latest_${branch//[^a-zA-Z0-9_.-]/.}" # Replace all special characters by a dot
          version="0.$(date +'%Y%m%d.%H%M%S')-${tag}"
          echo DO_BUILD=true >> $GITHUB_ENV # We always want to do a build if we're building a branch
          echo BRANCH=${branch} >> $GITHUB_ENV
          echo RELEASE_TAG=${tag} >> $GITHUB_ENV
          echo RELEASE_VERSION=${version} >> $GITHUB_ENV
          echo DOCKER_TAG=${tag} >> $GITHUB_ENV
          if [ "${branch}" == "main" ]; then
             echo DOCKER_EXTRA_TAGS=latest_rc >> $GITHUB_ENV      
          fi
          
          if git ls-remote --exit-code origin refs/tags/${tag} >/dev/null 2>&1; then
            echo "Found tag ${tag}, development release will be published"
            echo DO_RELEASE=true >> $GITHUB_ENV
          else 
            echo "Tag ${tag} does not exist, no development release will be published"
          fi
          
      - name: Build development release
        if: env.DO_BUILD
        run: ./gradlew dist distThirdParty -Pversion=${{env.RELEASE_VERSION}}
        
      - name: Publish build artifacts
        if: env.DO_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ env.DIST_DIR }}
        
      - name: Publish Docker image
        if: env.DO_RELEASE
        run: ./gradlew jib -Pversion=${{env.RELEASE_VERSION}} -PjibImageTag=${{env.DOCKER_TAG}} -PjibExtraImageTags=${{env.DOCKER_EXTRA_TAGS}}
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Update development release tag
        uses: richardsimko/update-tag@v1
        if: env.DO_RELEASE
        with:
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Create pre-release
        if: env.DO_RELEASE
        run: |
          files=$(find "${{ env.DIST_DIR }}" -type f -printf "%p ")
          gh release delete ${{ env.RELEASE_TAG }} -y || true
          gh release create ${{ env.RELEASE_TAG }} -p -t "Development Release - ${{ env.BRANCH }} branch" -n 'See `Assets` section below for latest build artifacts' ${files}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      
          
      

      